In [5]:
import numpy as np

a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c.shape

(12288, 45)

In [20]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [21]:
c.shape

(3, 3)

In [22]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
B.shape

(4, 1)

In [24]:
A,B

(array([[-0.57451568, -0.10440374, -1.10316433],
        [-2.3666618 ,  2.53551021,  0.72626145],
        [-0.81804143,  1.70996472, -1.20141192],
        [-0.45140239,  1.00492585,  1.25240559]]), array([[-1.78208375],
        [ 0.89510986],
        [-0.30948863],
        [ 1.80592905]]))

In [27]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[ 0.91639635, -3.28284059,  0.89492576],
       [ 0.28452725,  0.04606661, -0.06848188],
       [-0.28437221,  0.14630804,  0.08189216]])

In [29]:
a = np.random.rand(3, 3)
b = np.random.rand(3, 1)
c = a*b
c

array([[0.64894485, 0.63821179, 0.68492283],
       [0.59234518, 0.06231588, 0.39078185],
       [0.57916702, 0.08901117, 0.54398343]])

In [30]:
W = np.random.randn(3,3,4,8)
b = np.random.randn(1,1,1,8)
W,b

(array([[[[-2.31866898e-01,  1.12780890e-01, -2.98040669e-01,
           -9.73553365e-01,  5.95778133e-01,  6.51889989e-01,
            7.46185967e-01,  5.84497152e-01],
          [-5.52978573e-01,  7.55224050e-01,  1.67464504e-01,
            1.19597360e+00, -4.22461337e-01,  5.64574914e-01,
            5.67149681e-01, -9.41406831e-01],
          [-4.44433216e-01,  2.86879257e-01,  3.60898748e-01,
           -7.44254156e-01,  3.51917740e-01, -1.67616869e+00,
           -1.63240839e+00, -3.54458026e-02],
          [-1.29877299e+00, -1.09478052e+00,  3.05889855e-01,
           -2.73066925e-01,  2.09297133e+00, -1.38879137e+00,
            2.00289796e+00, -5.47121181e-02]],
 
         [[-4.17848830e-01, -1.32220574e+00, -4.10044635e-01,
            3.51119368e-01, -6.41907850e-01,  6.34180832e-02,
           -1.14202116e+00, -2.30554216e+00],
          [ 2.12316925e-02,  2.05068797e+00,  9.81965673e-02,
            3.93093966e-01, -1.15806866e+00, -8.51456220e-01,
           -1.16468198e

In [46]:
W[:,:,:,2]

array([[[-0.29804067,  0.1674645 ,  0.36089875,  0.30588986],
        [-0.41004464,  0.09819657,  0.26255722,  0.56035103],
        [ 0.34334436, -0.42409703, -0.72780368, -0.45426963]],

       [[ 2.36028929,  0.15331381,  1.9721039 ,  0.33299371],
        [ 0.54619635,  0.76529443, -1.1279466 , -2.04902419],
        [-0.33969979,  1.13602959,  1.684744  , -0.58728538]],

       [[ 1.36996864, -0.07289707,  1.1077503 , -0.28344535],
        [-0.57012882,  0.41696901,  2.27298187, -1.29830443],
        [ 1.0204229 , -0.15690981,  0.14232733, -1.23875938]]])